// flow-typed signature: a9bc0fb73c1b0df38fc25cdf873ea56f
// flow-typed version: <<STUB>>/scss-resets_v0.5.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scss-resets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scss-resets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scss-resets/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scss-resets/gulpfile.js' {
  declare module.exports: $Exports<'scss-resets/gulpfile'>;
}
declare module 'scss-resets/index' {
  declare module.exports: $Exports<'scss-resets'>;
}
declare module 'scss-resets/index.js' {
  declare module.exports: $Exports<'scss-resets'>;
}
